backend:
  name: git-gateway
  branch: main 
media_folder: static/images/
public_folder: /images/
locale: 'pt'
collections:
  - label: "Catálogo"
    name: "post"
    folder: "content/post"
    create: true
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Referência", name: "description", widget: "string"}
      - {label: "Categoria", name: "categories", widget: "string"}
      - {label: "Imagem", name: "image", widget: "image"}         
      - {label: "Fotos", name: "body", widget: "markdown"}
      
