backend:
  name: git-gateway
  branch: main
media_folder: static/images/
public_folder: /images/
locale: 'pt'
collections:
  - name: "posts"
    identifier_field: "title"
    label: "Páginas"
    label_singular: "Página"
    folder: "content/posts"
    create: true
    fields:
      - { name: "layout", label: "Layout", widget: "hidden", default: "redirect", required: true }  
      - { name: "title", label: "Nome", widget: "string", required: true }
      - { name: "slug", label: "Slug", widget: "string", required: true }
      - { name: "redirect_url", label: "Link do Google Drive", widget: "string", default: "#", required: true }